### ISSUE TITLE
Unable to Resolve service for type 'Fluxor.IDispatcher' -> Help Wanted

### ISSUE THREAD

**Issue by Dmo16** [mrpmorris/Fluxor#138]
I have just today run into the below exceptions and stacktrace when attempting to launch my Blazor Server project:

I don't believe it's related to the update for .NET 5 in v 3.9, but it's possible.

I think it's more likely I messed something up on my own.

Here is a small snapshot of my Startup.cs

`            services.AddScoped<UserRepository>();
            services.AddScoped<IAimRepository<Owner>, OwnerRepository>();
            services.AddScoped<IAimNoImageRepository<RaceTeamAttributes>, RaceTeamAttributeRepository>();
            services.AddScoped<IStateFacade, StateFacade>();
            services.AddFluxor(options =>
            {
                options.ScanAssemblies(typeof(Startup).Assembly,typeof(StateBase).Assembly);
                options.UseReduxDevTools();
            });
            
            services.AddScoped<IFileStorageService, AzureStorageService>();
            services.AddFormValidation(config =>
                config
                    .AddDataAnnotationsValidation()
                    .AddFluentValidation(typeof(Startup).Assembly)
            );`

If I remove the registration of my StateFacade service, The only change is that the stack trace begins at the "Fluxor.IFeature" level, which as you can see by the trace below, occurs a little further down if I do have the StateFacade registered.

I thought I'd created a DI loop somewhere accidently but this far, I haven't been able to locate one if that's the issue.

If I left anything out that is required to help set me straight, please advise.

`Unhandled exception. System.AggregateException: Some services are not able to be constructed (Error while validating the service descriptor 'ServiceType: FLuxorStore.Services.IStateFacade Lifetime: Scoped ImplementationType: FLuxorStore.Services.StateFacade': Unable to resolve service for type 'Fluxor.IDispatcher' while attempting to activate 'FLuxorStore.Services.StateFacade'.) (Error while validating the service descriptor 'ServiceType: Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware Lifetime: Scoped ImplementationType: Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware': Unable to resolve service for type 'Fluxor.IFeature`1[Fluxor.Blazor.Web.Middlewares.Routing.RoutingState]' while attempting to activate 'Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware'.) (Error while validating the service descriptor 'ServiceType: Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware Lifetime: Scoped ImplementationType: Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware': Unable to resolve service for type 'Fluxor.IFeature`1[Fluxor.Blazor.Web.Middlewares.Routing.RoutingState]' while attempting to activate 'Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware'.)
 ---> System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: FLuxorStore.Services.IStateFacade Lifetime: Scoped ImplementationType: FLuxorStore.Services.StateFacade': Unable to resolve service for type 'Fluxor.IDispatcher' while attempting to activate 'FLuxorStore.Services.StateFacade'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Fluxor.IDispatcher' while attempting to activate 'FLuxorStore.Services.StateFacade'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.ServiceCollectionContainerBuilderExtensions.BuildServiceProvider(IServiceCollection services, ServiceProviderOptions options)
   at Microsoft.Extensions.DependencyInjection.DefaultServiceProviderFactory.CreateServiceProvider(IServiceCollection containerBuilder)
   at Microsoft.Extensions.Hosting.Internal.ServiceFactoryAdapter`1.CreateServiceProvider(Object containerBuilder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at AiManager.Server.Program.Main(String[] args) in C:\Users\david\RiderProjects\AIM\src\AiManager.Server\Program.cs:line 11
 ---> (Inner Exception #1) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware Lifetime: Scoped ImplementationType: Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware': Unable to resolve service for type 'Fluxor.IFeature`1[Fluxor.Blazor.Web.Middlewares.Routing.RoutingState]' while attempting to activate 'Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Fluxor.IFeature`1[Fluxor.Blazor.Web.Middlewares.Routing.RoutingState]' while attempting to activate 'Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)<---

 ---> (Inner Exception #2) System.InvalidOperationException: Error while validating the service descriptor 'ServiceType: Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware Lifetime: Scoped ImplementationType: Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware': Unable to resolve service for type 'Fluxor.IFeature`1[Fluxor.Blazor.Web.Middlewares.Routing.RoutingState]' while attempting to activate 'Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware'.
 ---> System.InvalidOperationException: Unable to resolve service for type 'Fluxor.IFeature`1[Fluxor.Blazor.Web.Middlewares.Routing.RoutingState]' while attempting to activate 'Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware'.
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(ResultCache lifetime, Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain, Int32 slot)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.GetCallSite(ServiceDescriptor serviceDescriptor, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   --- End of inner exception stack trace ---
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.ValidateService(ServiceDescriptor descriptor)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider..ctor(IEnumerable`1 serviceDescriptors, IServiceProviderEngine engine, ServiceProviderOptions options)<---`

**Comment by mrpmorris** [comment]
You are injecting the routing middleware but haven't specified it in your AddFluxor code, so it won't be registered to be injected.

**Comment by Dmo16** [comment]
Hmm, interesting. To my knowledge I've never attempted to add any Middleware yet.

I'll triple check everything.

**Comment by mrpmorris** [comment]
If you want to share source I'll have a look

**Comment by Dmo16** [comment]
I'm digging through the code now to see if somehow I added something accidentally that wouldn't trigger a complaint from the IDE. 

I sincerely appreciate the offer to check and if I get nowhere, I'll add you to the repo. It would be quicker if you looked right away of course but, I like to try and solve things on my own before calling in the big guns. :D

**Comment by Dmo16** [comment]
I fixed it. I believe the issue was the way I was naming some Reducers and Action classes.

**Comment by mrpmorris** [comment]
Could you show me an example?

**Comment by Dmo16** [comment]
I thought I had fixed it, and broke it again.

Here was the issue: 

`       [ReducerMethod]
        public static RaceTeamAttributeState LoadRaceTeamAttributesSuccessActionReducer(LoadRaceTeamAttributesSuccessAction action) =>
            new RaceTeamAttributeState(false, null, action.Attributes, false);`

I had several reducers that didn't require either state, or action, and so I left them out of the injection. The Reducers require both though, even if you don't use them.

All fixed now, was my own fault.

**Comment by mrpmorris** [comment]
You can omit the action by specifying it as a parameter on the `[ReducerMethod]` like this...

`[ReducerMethod(typeof(MyAction))]`

**Comment by Dmo16** [comment]
Good to know, thanks Peter!
