### ISSUE TITLE
ConfigureAwait(false) in Effect results in exception

### ISSUE THREAD

**Issue by JEnrightDev** [mrpmorris/Fluxor#20]
When implementing an effect, if you return from a sub-task with ConfigureAwait(false), you will be greeted with a lovely exception.

```
The current thread is not associated with the Dispatcher. Use InvokeAsync() to switch execution to the Dispatcher when triggering rendering or component state.

   at Microsoft.AspNetCore.Components.Dispatcher.AssertAccess()
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.AddToRenderQueue(Int32 componentId, RenderFragment renderFragment)
   at Microsoft.AspNetCore.Components.ComponentBase.StateHasChanged()
   at Fluxor.Blazor.Web.Components.FluxorComponent.<OnInitialized>b__3_0(IState _)
   at Fluxor.Blazor.Web.Components.StateSubscriber.<>c__DisplayClass2_1.<Subscribe>b__1(Object s, EventArgs a)
   at Fluxor.Feature`1.TriggerStateChangedCallbacks(TState newState)
   at Fluxor.Feature`1.set_State(TState value)
   at Fluxor.Store.DequeueActions()
   at Fluxor.Store.Dispatch(Object action)
   at ....my-project..../GlobalStore.cs:line 62
```

Simple Example:

```csharp
                [EffectMethod]
                protected async Task HandleEffect(LoadAllTaskSettingsAction action, IDispatcher dispatcher)
                {
                    try
                    {
                        dispatcher.Dispatch(new Update("Handling effect for LoadAllTaskSettingsAction"));

                        dispatcher.Dispatch(new Success(await _settings.GetAllSettingsAsync().ConfigureAwait(false)));
                    }
                    catch (Exception ex)
                    {
                        dispatcher.Dispatch(new Failure(ex));
                    }
                }
```

**Comment by mrpmorris** [comment]
I'll look at it, thanks

**Comment by mrpmorris** [comment]
There is a preview release that fixes this. Would you like to try it?

**Comment by JEnrightDev** [comment]
> There is a preview release that fixes this. Would you like to try it?

Looks like it works now. Thanks!
