### ISSUE TITLE
Could not find 'tryInitializeFluxor'

### ISSUE THREAD

**Issue by paburgos** [mrpmorris/Fluxor#248]
Hello,

I have an issue using Fluxor when I change from "ASPNETCORE_ENVIRONMENT": "Development"  to "ASPNETCORE_ENVIRONMENT": "Staging"  This is the error:

> Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer: Warning: Unhandled exception rendering component: JavaScript error

> Fluxor.Exceptions.StoreInitializationException: JavaScript error
 ---> Microsoft.JSInterop.JSException: Could not find 'tryInitializeFluxor' ('tryInitializeFluxor' was undefined).
> Error: Could not find 'tryInitializeFluxor' ('tryInitializeFluxor' was undefined).
    at https://localhost:44303/_framework/blazor.server.js:1:497
    at Array.forEach (<anonymous>)
    at i.findFunction (https://localhost:44303/_framework/blazor.server.js:1:465)
    at E (https://localhost:44303/_framework/blazor.server.js:1:2606)
    at https://localhost:44303/_framework/blazor.server.js:1:3494
    at new Promise (<anonymous>)
    at Tt.beginInvokeJSFromDotNet (https://localhost:44303/_framework/blazor.server.js:1:3475)
    at https://localhost:44303/_framework/blazor.server.js:1:71773
    at Array.forEach (<anonymous>)
    at Tt._invokeClientMethod (https://localhost:44303/_framework/blazor.server.js:1:71759)
   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](Int64 targetInstanceId, String identifier, Object[] args)
   at Fluxor.Blazor.Web.StoreInitializer.OnAfterRenderAsync(Boolean firstRender)
   --- End of inner exception stack trace ---
   at Fluxor.Blazor.Web.StoreInitializer.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
> Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'EzxHmQbVA_FdnkGFsz2wRAuze8qqrHRpxohNnnfHtso'.

I am not sure what could be wrong, is there a way to manually load tryInitializeFluxor?

**Comment by paburgos** [comment]
I found the answer heck this [post](https://stackoverflow.com/questions/70501115/jsinterop-seems-to-stop-working-on-blazor-server-when-environment-is-changed/70501485#70501485)

**Comment by mrpmorris** [comment]
Interesting. Thanks for coming back and posting the answer!
