### ISSUE TITLE
provide document for update from version 4.2.1 to version 5

### ISSUE THREAD

**Issue by davidkmitrais** [mrpmorris/Fluxor#334]
Hi, I use the fluxor version 4.2.1 in my blazor WA app. 
Its been working fine with State, Feature, Reducer, Effect.
but when I update to version 5, seems it has broken everywhere.

Could we have a tutorial or sample on how we could update from version 4.2.1 to 5?

Thanks.

**Comment by mrpmorris** [comment]
My guess is that you are dispatching actions from App.razor before the app has even rendered, is that correct?

If not, I'll definitely need more info than "broken everywhere" or I'll just say "I've fixed everywhere" :)

**Comment by davidkmitrais** [comment]
Hi, so I my app is working fine on version 4.2.1.
Then now I'm update the latest version 5.9.1. 
The build is success, but I get the error below:

> Fluxor.Exceptions.StoreInitializationException: Store initialization error
 ---> System.TypeLoadException: Could not load type 'Fluxor.Extensions.SpinLockExtensions' from assembly 'Fluxor, Version=5.9.1.0, Culture=neutral, PublicKeyToken=6e6412da1d5ce8eb'.
   at Fluxor.Blazor.Web.ReduxDevTools.ReduxDevToolsMiddleware.AfterDispatch(Object action)
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at Fluxor.Store.DequeueActions() in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor\Store.cs:line 294
   at Fluxor.Store.ActivateStoreAsync() in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor\Store.cs:line 269
   at Fluxor.Store.InitializeAsync() in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor\Store.cs:line 115
   at Fluxor.Blazor.Web.StoreInitializer.OnAfterRenderAsync(Boolean firstRender)
   --- End of inner exception stack trace ---
   at Fluxor.Blazor.Web.StoreInitializer.OnAfterRenderAsync(Boolean firstRender)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.GetErrorHandledTask(Task taskToHandle, ComponentState owningComponentState)
Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost: Error: Unhandled exception in circuit 'F-5h3HgI9L4mUZA68_O6zoJOil5a8rghXHqgQTNh0zA'.
