### ISSUE TITLE
ReduxDevToolsMiddleware: An exception occurred while dispatching a location changed event

### ISSUE THREAD

**Issue by mohaaron** [mrpmorris/Fluxor#446]
I'm getting the following error in the Counter component after adding my state object to it. Any idea why? I've been receiving this error in another project as well and had to remove DevTools from the configuration to get rid of the error.

https://github.com/mohaaron/Syncfusion.Blazor.Demo/blob/trunk/BlazorSyncfusion.Demo/Pages/Counter.razor

fail: Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost[219]
      Location change to 'https://localhost:7081/counter' in circuit '_yK0X86L7bjCCtBD30RGdUhSceak5-gO6A2Yub-Ve5M' failed.
      Microsoft.AspNetCore.Components.LocationChangeException: An exception occurred while dispatching a location changed event.
       ---> System.NullReferenceException: Object reference not set to an instance of an object.
         at Fluxor.Blazor.Web.ReduxDevTools.ReduxDevToolsMiddleware.<>c.<AfterDispatch>b__12_0(StackFrame x) in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor.Blazor.Web.ReduxDevTools\ReduxDevToolsMiddleware.cs:line 65
         at System.Linq.Enumerable.SelectArrayIterator`2.MoveNext()
         at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
         at System.Linq.Enumerable.EnumerablePartition`1.MoveNext()
         at System.String.Join(String separator, IEnumerable`1 values)
         at Fluxor.Blazor.Web.ReduxDevTools.ReduxDevToolsMiddleware.AfterDispatch(Object action) in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor.Blazor.Web.ReduxDevTools\ReduxDevToolsMiddleware.cs:line 61
         at Fluxor.Store.<>c__DisplayClass38_0.<ExecuteMiddlewareAfterDispatch>b__0(IMiddleware x) in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor\Store.cs:line 256
         at System.Collections.Generic.List`1.ForEach(Action`1 action)
         at Fluxor.Store.ExecuteMiddlewareAfterDispatch(Object actionJustDispatched) in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor\Store.cs:line 256
         at Fluxor.Store.DequeueActions() in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor\Store.cs:line 294
         at Fluxor.Store.ActionDispatched(Object sender, ActionDispatchedEventArgs e) in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor\Store.cs:line 173
         at Fluxor.Dispatcher.Dispatch(Object action) in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor\Dispatcher.cs:line 47
         at Fluxor.Blazor.Web.Middlewares.Routing.RoutingMiddleware.LocationChanged(Object sender, LocationChangedEventArgs e) in C:\Data\Mine\Code\Fluxor\Source\Lib\Fluxor.Blazor.Web\Middlewares\Routing\RoutingMiddleware.cs:line 49
         at Microsoft.AspNetCore.Components.NavigationManager.NotifyLocationChanged(Boolean isInterceptedLink)
         --- End of inner exception stack trace ---
         at Microsoft.AspNetCore.Components.NavigationManager.NotifyLocationChanged(Boolean isInterceptedLink)
         at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.<>c__DisplayClass49_0.<OnLocationChangedAsync>b__0()
         at Microsoft.AspNetCore.Components.Rendering.RendererSynchronizationContext.<>c.<InvokeAsync>b__8_0(Object state)
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Components.Server.Circuits.CircuitHost.OnLocationChangedAsync(String uri, String state, Boolean intercepted)

**Comment by mrpmorris** [comment]
The repo is no longer present.
