### ISSUE TITLE
Null Refrence When Disposing Object

### ISSUE THREAD

**Issue by TheLazyLemur** [mrpmorris/Fluxor#80]
## Version Of Blazor 
- Blazor Server

## Issue

I am currently having an issue when I try go to another route. The issue occurs weather I use an "a" tag or the navigation manager built into Blazor. 
When I route I get the error :
```
[2020-08-18T12:48:27.447Z] Error: System.AggregateException: Exceptions were encountered while disposing components. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Fluxor.Blazor.Web.Components.FluxorComponent.Dispose(Boolean disposing)
   at Fluxor.Blazor.Web.Components.FluxorComponent.Dispose()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.TryDisposeInBatch(RenderBatchBuilder batchBuilder, Exception& exception)
   --- End of inner exception stack trace ---
 ---> (Inner Exception #1) System.NullReferenceException: Object reference not set to an instance of an object.
   at Fluxor.Blazor.Web.Components.FluxorComponent.Dispose(Boolean disposing)
   at Fluxor.Blazor.Web.Components.FluxorComponent.Dispose()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.TryDisposeInBatch(RenderBatchBuilder batchBuilder, Exception& exception)<---

 ---> (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at Fluxor.Blazor.Web.Components.FluxorComponent.Dispose(Boolean disposing)
   at Fluxor.Blazor.Web.Components.FluxorComponent.Dispose()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.TryDisposeInBatch(RenderBatchBuilder batchBuilder, Exception& exception)<---

 ---> (Inner Exception #3) System.NullReferenceException: Object reference not set to an instance of an object.
   at Fluxor.Blazor.Web.Components.FluxorComponent.Dispose(Boolean disposing)
   at Fluxor.Blazor.Web.Components.FluxorComponent.Dispose()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.TryDisposeInBatch(RenderBatchBuilder batchBuilder, Exception& exception)<---
```
if i try to manually override dispose I get a null refrence where ```base.Dispose(disposed);``` is called:
```
 (Inner Exception #2) System.NullReferenceException: Object reference not set to an instance of an object.
   at Fluxor.Blazor.Web.Components.FluxorComponent.Dispose(Boolean disposing)
   at EdenXRPlatform.Components.Reporting.Dashboard.Charts.Engagement.Dispose(Boolean disposed) in /home/dan/Workspace/Eden/XRPlatform/EdenXRPlatform/Components/Reporting/Dashboard/Charts/Engagement.razor.cs:line 32
   at Fluxor.Blazor.Web.Components.FluxorComponent.Dispose()
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.TryDisposeInBatch(RenderBatchBuilder batchBuilder, Exception& exception)<---
```

**Comment by TheLazyLemur** [comment]
## Solution
I just had not called ```base.OnInitialized();``  in the components  ```OnInitialized``
